version: 2

updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore:"
    labels:
      - "npm dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci:"
      labels:
        - "github dependencies"
