version: '3.9'

services:
  postgresql:
    container_name: feedbackio-db
    image: postgres:13-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: feedbackio
      POSTGRES_PASSWORD: feedbackiopg
      POSTGRES_DB: feedbackiodb
    networks:
      - feedbackio

  api:
    container_name: feedbackio-api
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: Dockerfile
    image: feedbackio:0.1
    restart: always
    env_file: .env
    environment:
      DATABASE_URL: postgres://feedbackio:feedbackiopg@postgresql:5432/feedbackiodb
    ports:
      # This maps port from .env on the host to same port number on the container.
      - '$PORT:$PORT'
    networks:
      - feedbackio

networks:
  feedbackio:
    driver: bridge

volumes:
  dbdata:
