name: 'Auto Merge Dependabot'

on:
  check_suite:
    types:
      - completed

jobs:
  merge:
    needs: [build, analyze]
    if: ${{ github.actor == 'dependabot[bot]' && success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
