name: Main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16-alpine

    services:
      database:
        image: postgres:14-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: buzzl
          POSTGRES_DB: buzzl
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Check commit message
      #   uses: wagoid/commitlint-github-action@v4.1.9

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ~/.cache/yarn/v6
          key: ${{runner.os}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-yarn-

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile --cache-folder ~/.cache/yarn/v6

      - name: Run linting
        run: yarn lint

      - name: Run code style
        run: yarn style

      - name: Run tests
        run: yarn typeorm migration:run && yarn test:ci
        env:
          NODE_ENV: 'test'
          DATABASE_URL: 'postgres://postgres:buzzl@database:5432/buzzl'
          ACCESS_TOKEN_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQC/J/7wicw1xTHqFGR8/viU9xn5IPQWjYijAE0wVTwQUiGpu3Mv\nW3wxxDIDUGa+FtlJhnibzIv5sNScQzPiK+fWeHbzNT7rk9JZOVDar0BPyt9eNvBY\nUACoD7kmxY8khd4APnndotzpoyGJAd4H6kMUGoLEMO894L7OS5W2QSWDiwIDAQAB\nAoGBAIZMt1SPu6VbcgIfaapYCJXANcNOX68oqQK8R37Zo2VkDrqNNBPllo/wY6Lo\nbgbHTsnVbA8p2n4Gupk+rckNR8ey9gUrb8moaZJHf7UCvTW592Z/A3Nlf6Pdsw1R\netJmrwuC+l5ETnncm1vkhdjUBdtPZ98D/m0/zdqlz2s70sjBAkEA700ULnmeP2hf\nOfT2z5ZjpH7T2BKXtIwWdj7RO6cb0BH6rDAHeKZgZP2DswK0etaJlxuUevEfdq84\nzJW60hk/aQJBAMx+2RSTgGQHy8cU67XuD98MZ9GtreBQgsIdmbjrjG1Jr34yE+jN\nYA9i46kBoyGugeZI7VOTDOvsQPzMPz8cQNMCQC7pvXse/JcRrxl9nKU1pnMpKf7C\nJluO2xhzWDGJoTo5TBtVjyFn/J3P1XHSpe8u/+pPzdwMSU7LKydwcx+dM4ECQBB6\ndEGtNR5aZnhPXkMVwN+nX0JNLYKy2iaMPhPhnzo7QtH3dRVAX2o9/LxkrmGLb1pA\nLCec5OCp8/6q8rnCLBMCQGYP96OBuk9bhZx8Q45v9yzs/k9baAZwAJqdXrEQt4wd\nghviOqGHYs1JMdtMg7XHq/4vZn0HxtHifAz6u30yJrE=\n-----END RSA PRIVATE KEY-----\n"
          ACCESS_TOKEN_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC/J/7wicw1xTHqFGR8/viU9xn5\nIPQWjYijAE0wVTwQUiGpu3MvW3wxxDIDUGa+FtlJhnibzIv5sNScQzPiK+fWeHbz\nNT7rk9JZOVDar0BPyt9eNvBYUACoD7kmxY8khd4APnndotzpoyGJAd4H6kMUGoLE\nMO894L7OS5W2QSWDiwIDAQAB\n-----END PUBLIC KEY-----\n"
          ACCESS_TOKEN_EXPIRATION: '15m'

      - name: Build application
        run: yarn build

      - name: Get tests coverage with Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
