name: Main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:14-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: buzzl
          POSTGRES_DB: buzzl
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v4.1.9

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ~/.cache/yarn/v6
          key: ${{runner.os}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-yarn-

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile --cache-folder ~/.cache/yarn/v6

      - name: Run linting
        run: yarn lint

      - name: Run code style
        run: yarn style

      - name: Run tests
        run: yarn test:ci
        env:
          NODE_ENV: 'test'
          DATABASE_URL: 'postgres://postgres:buzzl@database:5432/buzzl'

      - name: Build application
        run: yarn build

      - name: Get tests coverage with Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
