name: New Features

on:
  push:
    branches:
      - 'feat/**'
      - 'refactor/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v3

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ~/.cache/yarn/v6
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile --cache-folder ~/.cache/yarn/v6

      - name: Run linting
        run: yarn lint

      - name: Run code style
        run: yarn style

      - name: Run tests
        run: yarn test
        env:
          NODE_ENV: 'test'

      - name: Build application
        run: yarn build
